project_id = "qbidsyeefbjhekiqvlqm"

[functions.openai-chat]
verify_jwt = true

[functions.voice-to-text]
verify_jwt = true

[functions.vision-analyze]
verify_jwt = true

[functions.notification-scheduler]
verify_jwt = false
