// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbidsyeefbjhekiqvlqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiaWRzeWVlZmJqaGVraXF2bHFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NjExNjAsImV4cCI6MjA2MjIzNzE2MH0.DUsmJ_fl0DtMEm74zUGUg7Cj3ZTZlg_858b2Un_H09w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});